<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEhJNe7O\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEhJNe7O/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEhJNe7O.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEhJNe7O\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEhJNe7O\App_KernelDevDebugContainer([
    'container.build_hash' => 'EhJNe7O',
    'container.build_id' => '6f2ec734',
    'container.build_time' => 1641328358,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEhJNe7O');
